apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-l4xo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0039-tenant/tkrw-pr712-0075-0039-app/devfile-sample-l4xo@sha256:0e0f5e306640fdcf0ef5923e15eb867640002ad36d636f4da19ae07262eff88e
        name: my-nodejs
        resources: {}
status: {}
